import Vue from 'vue';
import cBtn from '@/Components/cBtn';
import cSelect from '@/Components/cSelect';
import cInput from '@/Components/cInput';
import cSlider from '@/Components/cSlider';
import cDate from '@/Components/cDate';
import cTextArea from '@/Components/cTextArea';
import cTag from '@/Components/cTag';
import cPopUp from '@/Components/cPopUp';
import cCheckbox from '@/Components/cCheckbox';

Vue.component('cBtn', cBtn);
Vue.component('cSelect', cSelect);
Vue.component('cInput', cInput);
Vue.component('cSlider', cSlider);
Vue.component('cDate', cDate);
Vue.component('cTextArea', cTextArea);
Vue.component('cTag', cTag);
Vue.component('cPopUp', cPopUp);
Vue.component('cCheckbox', cCheckbox);